name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Release
        run: |
          npm ci
          npm run release
          cd dist
          zip -r -9 movement-pass_public-api_v1.zip *

      - name: Update
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && env.AWS_REGION != '' }}
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.2
        with:
          zip-file: ./dist/movement-pass_public-api_v1.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
